// Binary_converter.globals.c
// Generated by decompiling Binary_converter.exe
// using Reko decompiler version 0.9.0.0.

#include "Binary_converter.h"

Eq_1221 g_t020C;
Eq_5580 g_t400000 = 
	{
		0x0000,
		0,
	};
Eq_1224 g_t413AD0 = 
	{
		1,
		0x00413AD8,
	};
Eq_1224 g_t4140A4 = 
	{
		1,
		0x004140AC,
	};
Eq_1224 g_t4143D8 = 
	{
		1,
		0x004143E0,
	};
Eq_1224 g_t414C5C = 
	{
		1,
		0x00414C64,
	};
Eq_1224 g_t414F9C = 
	{
		1,
		0x00414FA4,
	};
Eq_1224 g_t4151B4 = 
	{
		1,
		0x004151BC,
	};
Eq_1224 g_t4153C0 = 
	{
		1,
		0x004153C8,
	};
Eq_1224 g_t4155D8 = 
	{
		1,
		0x004155E0,
	};
Eq_1224 g_t4157F8 = 
	{
		1,
		0x00415800,
	};
Eq_1224 g_t416280 = 
	{
		3,
		0x00416288,
	};
Eq_1224 g_t4179A8 = 
	{
		1,
		0x004179B0,
	};
Eq_1224 g_t418044 = 
	{
		1,
		0x0041804C,
	};
Eq_1224 g_t41875C = 
	{
		1,
		0x00418764,
	};
Eq_1224 g_t418A5C = 
	{
		1,
		0x00418A64,
	};
Eq_1224 g_t419074 = 
	{
		1,
		0x0041907C,
	};
Eq_1224 g_t419640 = 
	{
		1,
		0x00419648,
	};
Eq_1224 g_t419750 = 
	{
		1,
		0x00419758,
	};
Eq_1224 g_t41A910 = 
	{
		1,
		0x0041A918,
	};
Eq_1224 g_t41BAB4 = 
	{
		3,
		0x0041BABC,
	};
char g_str4264A4[] = "invalid string position";
char g_str4264C0[] = "string too long";
Eq_35 g_a4265B0[] = 
	{
	};
Eq_35 g_t4265C4 = 
	{
		0x70
	};
word32 g_a4265C8[] = 
	{
	};
char g_str4265E0[] = "Stack around the variable '";
char g_str4265FC[] = "' was corrupted.";
Eq_1019 g_t426C70 = 
	{
		&g_dw429370,
		&g_dw4293C0,
	};
word32 g_dw426D6C = 0x00690062;
word32 g_dw426D70 = 0x005C006E;
word32 g_dw426D74 = 0x0053004D;
word32 g_dw426D78 = 0x00440050;
word32 g_dw426D7C = 0x00310042;
word32 g_dw426D80 = 0x00300034;
word32 g_dw426D84 = 0x0044002E;
word32 g_dw426D88 = 0x004C004C;
word16 g_w426D8C = 0x0000;
wchar_t g_str426F20[] = "D\0L\0L\0\0";
wchar_t g_str426F2C[] = "M\0S\0P\0D\0B\01\04\00\0\0";
word32 g_dw429000 = 0x00000072;
word32 g_dw429004 = 0x00000002;
ptr32 g_ptr429010 = 0x44BF19B1;
Eq_1247 g_t429014 = 
	{
		0xBB40E64E
	};
ui32 g_dw42901C = 0x00000001;
word32 g_a429020[] = 
	{
	};
word32 g_dw429028 = 0x00000001;
word32 g_dw42903C = 0x00000001;
byte g_b429318 = 0x00;
word32 g_dw429324 = 0x00000000;
word32 g_dw429328 = 0x00000000;
byte g_b42932C = 0x00;
word32 g_dw429350 = 0x00000000;
ui32 g_dw429354 = 0x00000000;
word32 g_dw42935C = 0x00000000;
word32 g_dw429370 = 0x00000000;
word32 g_dw429374 = 0x00000000;
Eq_35 g_t42937C = 
	{
		0x00
	};
word32 g_dw429380 = 0x00000000;
word32 g_dw429384 = 0x00000000;
word32 g_dw4293C0 = 0x00000000;
struct Eq_16068 * g_ptr42944C = null;
struct Eq_16065 * g_ptr429450 = null;
struct Eq_27 * g_ptr429454 = null;
struct Eq_28 * g_ptr429458 = null;
Eq_35 g_t42945C = 
	{
		0x00
	};
Eq_35 g_t429460 = 
	{
		0x00
	};
Eq_35 g_t429464 = 
	{
		0x00
	};
Eq_35 g_t429468 = 
	{
		0x00
	};
Eq_1247 g_t42946C = 
	{
		0x00000000
	};
word32 g_dw429470 = 0x00000000;
struct Eq_1221 * g_ptr429474 = null;
Eq_35 g_t429478 = 
	{
		0x00
	};
struct Eq_16058 * g_ptr42947C = null;
Eq_16037 g_t429480 = 
	{
		0x00
	};
ptr32 g_ptr429484 = 0x00000000;
struct Eq_16055 * g_ptr429488 = null;
word32 g_dw42972C = 0x00000000;
word32 g_dw429730 = 0x00000000;
word32 g_dw429754 = 0x00000000;
byte g_b429758 = 0x00;
byte g_b429759 = 0x00;
Eq_35 g_t429774 = 
	{
		0x00
	};

